### ISSUE TITLE
Repack error Alice Parade

### ISSUE THREAD

**Issue by ghost** [marcussacana/UnisonShiftManager#4]
hi dude i unpacked the alice parade game data.pac file to translate it using GARbro and im trying to repack it with unipac but i get this error [(Link)](https://imgur.com/a/e81h5PR) and i dont understand what it means, , do you know what it means?

**Comment by marcussacana** [comment]
That's because you can repack files only if are extracted using unipac.
When unpacking with garbro you lose some informations about the PAC format, when you use the UniPac those data is exported as well.
If you have already modified any file you can extract the pac with unipac and replace the files that you modified.
